name: Hugo Tunius - Blog
description: >
  Personal blog of Hugo Tunius.
  Developer, open source enthusiast,
  aspiring designer, and Hugo of all trades.
markdown: kramdown
highligther: pygments
timezone: Europe/London
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: https://hugotunius.se
author: Hugo Tunius
copyright: Hugo Tunius
permalink: /:year/:month/:day/:title.html
plugins:
    - jekyll-gzip
    - jekyll-redirect-from
    - jekyll-feed
    - jekyll-sitemap
sass:
  style: compressed
  sass_dir: _sass
gzip:
  replace_files: true

